# -*- coding: utf-8 -*-
"""Step5_ADNI_histogram_calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znbgdN6pPQWk2odGauydnniJkXhlGJ2b
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_CN_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "DTI_parameters/DTI_parameters_46_diff_CN_updated"),
    "54": os.path.join(base_dir, "DTI_parameters/DTI_parameters_54_diff_CN_updated"),
    "55": os.path.join(base_dir, "DTI_parameters/DTI_parameters_55_diff_CN_updated"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_46_diff"),
    "54": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_54_diff"),
    "55": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_55"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_CN_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (CN case)
# ----------------------------------
subject_ids = sorted([
    '016_S_4952_F_73_CN', '024_S_6005_F_68_CN', '037_S_0303_M_95_CN', '032_S_0677_M_82_CN',
    '032_S_4277_F_77_CN', '024_S_4084_F_75_CN', '036_S_6088_F_69_CN', '033_S_0734_M_84_CN',
    '035_S_0156_M_86_CN', '037_S_4028_F_70_CN', '036_S_4389_M_87_CN', '033_S_1098_F_83_CN',
    '033_S_1016_F_89_CN', '032_S_4429_M_83_CN', '035_S_6156_M_76_CN', '032_S_1169_F_83_CN',
    '035_S_6160_M_61_CN', '033_S_4176_M_90_CN', '033_S_4177_M_91_CN', '020_S_6185_M_83_CN',
    '024_S_6184_F_71_CN', '035_S_4464_M_76_CN', '035_S_0555_M_88_CN', '020_S_6227_F_62_CN',
    '032_S_6211_M_81_CN', '032_S_6279_M_89_CN', '020_S_6282_M_76_CN', '032_S_6294_M_82_CN',
    '032_S_6293_F_86_CN', '016_S_6381_M_73_CN', '020_S_6449_F_66_CN', '020_S_6470_M_69_CN',
    '020_S_6504_M_69_CN', '020_S_6513_F_66_CN', '020_S_6566_M_73_CN', '032_S_6699_M_67_CN',
    '032_S_6709_F_69_CN', '032_S_6701_F_71_CN', '032_S_6717_M_75_CN', '016_S_6790_M_78_CN',
    '016_S_6834_F_82_CN', '016_S_6802_F_63_CN', '033_S_4179_M_91_CN', '016_S_6853_F_67_CN',
    '033_S_6298_F_72_CN', '016_S_6892_F_66_CN', '016_S_6931_M_73_CN', '016_S_6943_M_75_CN',
    '016_S_6941_M_62_CN', '033_S_6969_M_69_CN', '016_S_6971_M_73_CN', '016_S_6934_M_67_CN',
    '033_S_5198_F_78_CN', '033_S_6266_F_70_CN', '033_S_7100_M_73_CN', '033_S_6352_M_76_CN',
    '033_S_7114_F_66_CN', '033_S_6572_F_72_CN', '033_S_10215_F_56_CN', '033_S_10092_F_56_CN',
    '033_S_10175_M_70_CN','033_S_10099_M_66_CN','016_S_6773_F_55_CN', '037_S_4410_F_74_CN',
    '037_S_4071_M_90_CN', '037_S_6032_F_66_CN', '037_S_6031_F_67_CN', '041_S_4037_M_82_CN',
    '037_S_6046_M_76_CN', '068_S_4424_F_72_CN', '037_S_4308_M_80_CN', '041_S_4427_M_77_CN',
    '068_S_0473_M_84_CN', '068_S_0210_F_84_CN', '037_S_6115_F_71_CN', '037_S_6144_F_65_CN',
    '094_S_4649_M_71_CN', '094_S_6250_F_72_CN', '094_S_6269_F_70_CN', '041_S_6226_F_68_CN',
    '094_S_6275_F_58_CN', '041_S_6292_M_77_CN', '041_S_6314_M_76_CN', '094_S_6278_F_81_CN',
    '041_S_6401_M_77_CN', '094_S_6417_M_78_CN', '094_S_6419_M_76_CN', '094_S_6440_F_68_CN',
    '041_S_5100_M_80_CN', '041_S_6447_F_71_CN', '041_S_6785_F_66_CN', '041_S_6801_F_61_CN',
    '068_S_4340_F_75_CN', '041_S_4200_F_81_CN', '041_S_6136_M_63_CN', '041_S_6159_M_78_CN',
    '068_S_0127_M_86_CN', '041_S_6786_F_90_CN', '041_S_6354_F_76_CN', '041_S_6192_F_88_CN',
    '027_S_6327_F_77_CN', '027_S_6516_M_76_CN', '027_S_6183_M_68_CN', '027_S_6577_M_69_CN',
    '021_S_6896_M_65_CN', '027_S_0074_M_93_CN', '021_S_6910_F_77_CN', '021_S_6914_M_70_CN',
    '021_S_6918_M_57_CN', '021_S_6940_M_72_CN', '021_S_0337_M_93_CN', '021_S_6987_F_66_CN',
    '021_S_6994_F_61_CN', '027_S_6001_F_77_CN', '301_S_6224_F_79_CN','007_S_4637_F_71_CN',
    '003_S_4839_M_66_CN','003_S_4840_F_62_CN', '003_S_4872_F_69_CN', '003_S_4119_M_80_CN',
    '021_S_4558_F_71_CN', '021_S_4276_F_83_CN', '016_S_4688_F_83_CN','027_S_5093_F_77_CN',
    '016_S_4121_M_91_CN', '016_S_4951_F_75_CN', '021_S_4421_F_77_CN', '027_S_5083_M_74_CN', '027_S_5169_F_66_CN',
    '027_S_0120_M_83_CN', '021_S_4335_F_77_CN', '021_S_6312_M_80_CN', '027_S_6317_F_81_CN'
])

# ----------------------------------
# Extract features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        fa_file = os.path.join(subj_dir, f"tensor_fa_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(fa_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (FA or atlas not found)")
        continue

    # Load FA and atlas
    fa_data = nib.load(fa_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = fa_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# Save results
np.save(os.path.join(output_dir, "Histogram_CN_FA_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_CN_FA_subjects.npy"), np.array(subj_included))

print(f"FA: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (CN, FA only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_CN_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "DTI_parameters/DTI_parameters_46_diff_CN_updated"),
    "54": os.path.join(base_dir, "DTI_parameters/DTI_parameters_54_diff_CN_updated"),
    "55": os.path.join(base_dir, "DTI_parameters/DTI_parameters_55_diff_CN_updated"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_46_diff"),
    "54": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_54_diff"),
    "55": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_55"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_CN_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (CN case)
# ----------------------------------
subject_ids = sorted([
    '016_S_4952_F_73_CN', '024_S_6005_F_68_CN', '037_S_0303_M_95_CN', '032_S_0677_M_82_CN',
    '032_S_4277_F_77_CN', '024_S_4084_F_75_CN', '036_S_6088_F_69_CN', '033_S_0734_M_84_CN',
    '035_S_0156_M_86_CN', '037_S_4028_F_70_CN', '036_S_4389_M_87_CN', '033_S_1098_F_83_CN',
    '033_S_1016_F_89_CN', '032_S_4429_M_83_CN', '035_S_6156_M_76_CN', '032_S_1169_F_83_CN',
    '035_S_6160_M_61_CN', '033_S_4176_M_90_CN', '033_S_4177_M_91_CN', '020_S_6185_M_83_CN',
    '024_S_6184_F_71_CN', '035_S_4464_M_76_CN', '035_S_0555_M_88_CN', '020_S_6227_F_62_CN',
    '032_S_6211_M_81_CN', '032_S_6279_M_89_CN', '020_S_6282_M_76_CN', '032_S_6294_M_82_CN',
    '032_S_6293_F_86_CN', '016_S_6381_M_73_CN', '020_S_6449_F_66_CN', '020_S_6470_M_69_CN',
    '020_S_6504_M_69_CN', '020_S_6513_F_66_CN', '020_S_6566_M_73_CN', '032_S_6699_M_67_CN',
    '032_S_6709_F_69_CN', '032_S_6701_F_71_CN', '032_S_6717_M_75_CN', '016_S_6790_M_78_CN',
    '016_S_6834_F_82_CN', '016_S_6802_F_63_CN', '033_S_4179_M_91_CN', '016_S_6853_F_67_CN',
    '033_S_6298_F_72_CN', '016_S_6892_F_66_CN', '016_S_6931_M_73_CN', '016_S_6943_M_75_CN',
    '016_S_6941_M_62_CN', '033_S_6969_M_69_CN', '016_S_6971_M_73_CN', '016_S_6934_M_67_CN',
    '033_S_5198_F_78_CN', '033_S_6266_F_70_CN', '033_S_7100_M_73_CN', '033_S_6352_M_76_CN',
    '033_S_7114_F_66_CN', '033_S_6572_F_72_CN', '033_S_10215_F_56_CN', '033_S_10092_F_56_CN',
    '033_S_10175_M_70_CN','033_S_10099_M_66_CN','016_S_6773_F_55_CN', '037_S_4410_F_74_CN',
    '037_S_4071_M_90_CN', '037_S_6032_F_66_CN', '037_S_6031_F_67_CN', '041_S_4037_M_82_CN',
    '037_S_6046_M_76_CN', '068_S_4424_F_72_CN', '037_S_4308_M_80_CN', '041_S_4427_M_77_CN',
    '068_S_0473_M_84_CN', '068_S_0210_F_84_CN', '037_S_6115_F_71_CN', '037_S_6144_F_65_CN',
    '094_S_4649_M_71_CN', '094_S_6250_F_72_CN', '094_S_6269_F_70_CN', '041_S_6226_F_68_CN',
    '094_S_6275_F_58_CN', '041_S_6292_M_77_CN', '041_S_6314_M_76_CN', '094_S_6278_F_81_CN',
    '041_S_6401_M_77_CN', '094_S_6417_M_78_CN', '094_S_6419_M_76_CN', '094_S_6440_F_68_CN',
    '041_S_5100_M_80_CN', '041_S_6447_F_71_CN', '041_S_6785_F_66_CN', '041_S_6801_F_61_CN',
    '068_S_4340_F_75_CN', '041_S_4200_F_81_CN', '041_S_6136_M_63_CN', '041_S_6159_M_78_CN',
    '068_S_0127_M_86_CN', '041_S_6786_F_90_CN', '041_S_6354_F_76_CN', '041_S_6192_F_88_CN',
    '027_S_6327_F_77_CN', '027_S_6516_M_76_CN', '027_S_6183_M_68_CN', '027_S_6577_M_69_CN',
    '021_S_6896_M_65_CN', '027_S_0074_M_93_CN', '021_S_6910_F_77_CN', '021_S_6914_M_70_CN',
    '021_S_6918_M_57_CN', '021_S_6940_M_72_CN', '021_S_0337_M_93_CN', '021_S_6987_F_66_CN',
    '021_S_6994_F_61_CN', '027_S_6001_F_77_CN', '301_S_6224_F_79_CN','007_S_4637_F_71_CN',
    '003_S_4839_M_66_CN','003_S_4840_F_62_CN', '003_S_4872_F_69_CN', '003_S_4119_M_80_CN',
    '021_S_4558_F_71_CN', '021_S_4276_F_83_CN', '016_S_4688_F_83_CN','027_S_5093_F_77_CN',
    '016_S_4121_M_91_CN', '016_S_4951_F_75_CN', '021_S_4421_F_77_CN', '027_S_5083_M_74_CN', '027_S_5169_F_66_CN',
    '027_S_0120_M_83_CN', '021_S_4335_F_77_CN', '021_S_6312_M_80_CN', '027_S_6317_F_81_CN'
])

# ----------------------------------
# Extract AD features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        ad_file = os.path.join(subj_dir, f"tensor_ad_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(ad_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (AD or atlas not found)")
        continue

    # Load AD and atlas
    ad_data = nib.load(ad_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = ad_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# Save results
np.save(os.path.join(output_dir, "Histogram_CN_AD_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_CN_AD_subjects.npy"), np.array(subj_included))

print(f"AD: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (CN, AD only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_CN_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "DTI_parameters/DTI_parameters_46_diff_CN_updated"),
    "54": os.path.join(base_dir, "DTI_parameters/DTI_parameters_54_diff_CN_updated"),
    "55": os.path.join(base_dir, "DTI_parameters/DTI_parameters_55_diff_CN_updated"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_46_diff"),
    "54": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_54_diff"),
    "55": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_55"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_CN_All")
os.makedirs(output_dir, exist_ok=True)

roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (CN case)
# ----------------------------------
subject_ids = sorted([
    '016_S_4952_F_73_CN', '024_S_6005_F_68_CN', '037_S_0303_M_95_CN', '032_S_0677_M_82_CN',
    '032_S_4277_F_77_CN', '024_S_4084_F_75_CN', '036_S_6088_F_69_CN', '033_S_0734_M_84_CN',
    '035_S_0156_M_86_CN', '037_S_4028_F_70_CN', '036_S_4389_M_87_CN', '033_S_1098_F_83_CN',
    '033_S_1016_F_89_CN', '032_S_4429_M_83_CN', '035_S_6156_M_76_CN', '032_S_1169_F_83_CN',
    '035_S_6160_M_61_CN', '033_S_4176_M_90_CN', '033_S_4177_M_91_CN', '020_S_6185_M_83_CN',
    '024_S_6184_F_71_CN', '035_S_4464_M_76_CN', '035_S_0555_M_88_CN', '020_S_6227_F_62_CN',
    '032_S_6211_M_81_CN', '032_S_6279_M_89_CN', '020_S_6282_M_76_CN', '032_S_6294_M_82_CN',
    '032_S_6293_F_86_CN', '016_S_6381_M_73_CN', '020_S_6449_F_66_CN', '020_S_6470_M_69_CN',
    '020_S_6504_M_69_CN', '020_S_6513_F_66_CN', '020_S_6566_M_73_CN', '032_S_6699_M_67_CN',
    '032_S_6709_F_69_CN', '032_S_6701_F_71_CN', '032_S_6717_M_75_CN', '016_S_6790_M_78_CN',
    '016_S_6834_F_82_CN', '016_S_6802_F_63_CN', '033_S_4179_M_91_CN', '016_S_6853_F_67_CN',
    '033_S_6298_F_72_CN', '016_S_6892_F_66_CN', '016_S_6931_M_73_CN', '016_S_6943_M_75_CN',
    '016_S_6941_M_62_CN', '033_S_6969_M_69_CN', '016_S_6971_M_73_CN', '016_S_6934_M_67_CN',
    '033_S_5198_F_78_CN', '033_S_6266_F_70_CN', '033_S_7100_M_73_CN', '033_S_6352_M_76_CN',
    '033_S_7114_F_66_CN', '033_S_6572_F_72_CN', '033_S_10215_F_56_CN', '033_S_10092_F_56_CN',
    '033_S_10175_M_70_CN','033_S_10099_M_66_CN','016_S_6773_F_55_CN', '037_S_4410_F_74_CN',
    '037_S_4071_M_90_CN', '037_S_6032_F_66_CN', '037_S_6031_F_67_CN', '041_S_4037_M_82_CN',
    '037_S_6046_M_76_CN', '068_S_4424_F_72_CN', '037_S_4308_M_80_CN', '041_S_4427_M_77_CN',
    '068_S_0473_M_84_CN', '068_S_0210_F_84_CN', '037_S_6115_F_71_CN', '037_S_6144_F_65_CN',
    '094_S_4649_M_71_CN', '094_S_6250_F_72_CN', '094_S_6269_F_70_CN', '041_S_6226_F_68_CN',
    '094_S_6275_F_58_CN', '041_S_6292_M_77_CN', '041_S_6314_M_76_CN', '094_S_6278_F_81_CN',
    '041_S_6401_M_77_CN', '094_S_6417_M_78_CN', '094_S_6419_M_76_CN', '094_S_6440_F_68_CN',
    '041_S_5100_M_80_CN', '041_S_6447_F_71_CN', '041_S_6785_F_66_CN', '041_S_6801_F_61_CN',
    '068_S_4340_F_75_CN', '041_S_4200_F_81_CN', '041_S_6136_M_63_CN', '041_S_6159_M_78_CN',
    '068_S_0127_M_86_CN', '041_S_6786_F_90_CN', '041_S_6354_F_76_CN', '041_S_6192_F_88_CN',
    '027_S_6327_F_77_CN', '027_S_6516_M_76_CN', '027_S_6183_M_68_CN', '027_S_6577_M_69_CN',
    '021_S_6896_M_65_CN', '027_S_0074_M_93_CN', '021_S_6910_F_77_CN', '021_S_6914_M_70_CN',
    '021_S_6918_M_57_CN', '021_S_6940_M_72_CN', '021_S_0337_M_93_CN', '021_S_6987_F_66_CN',
    '021_S_6994_F_61_CN', '027_S_6001_F_77_CN', '301_S_6224_F_79_CN','007_S_4637_F_71_CN',
    '003_S_4839_M_66_CN','003_S_4840_F_62_CN', '003_S_4872_F_69_CN', '003_S_4119_M_80_CN',
    '021_S_4558_F_71_CN', '021_S_4276_F_83_CN', '016_S_4688_F_83_CN','027_S_5093_F_77_CN',
    '016_S_4121_M_91_CN', '016_S_4951_F_75_CN', '021_S_4421_F_77_CN', '027_S_5083_M_74_CN', '027_S_5169_F_66_CN',
    '027_S_0120_M_83_CN', '021_S_4335_F_77_CN', '021_S_6312_M_80_CN', '027_S_6317_F_81_CN'
])


# ----------------------------------
# Extract MD features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        md_file = os.path.join(subj_dir, f"tensor_md_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(md_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (MD or atlas not found)")
        continue

    # Load MD and atlas
    md_data = nib.load(md_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = md_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# Save results
np.save(os.path.join(output_dir, "Histogram_CN_MD_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_CN_MD_subjects.npy"), np.array(subj_included))

print(f"MD: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (CN, MD only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_CN_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "DTI_parameters/DTI_parameters_46_diff_CN_updated"),
    "54": os.path.join(base_dir, "DTI_parameters/DTI_parameters_54_diff_CN_updated"),
    "55": os.path.join(base_dir, "DTI_parameters/DTI_parameters_55_diff_CN_updated"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_46_diff"),
    "54": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_54_diff"),
    "55": os.path.join(base_dir, "updated_step5_registered_data/Registered_label_55"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_CN_All")
os.makedirs(output_dir, exist_ok=True)

roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]


n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (CN case)
# ----------------------------------
subject_ids = sorted([
    '016_S_4952_F_73_CN', '024_S_6005_F_68_CN', '037_S_0303_M_95_CN', '032_S_0677_M_82_CN',
    '032_S_4277_F_77_CN', '024_S_4084_F_75_CN', '036_S_6088_F_69_CN', '033_S_0734_M_84_CN',
    '035_S_0156_M_86_CN', '037_S_4028_F_70_CN', '036_S_4389_M_87_CN', '033_S_1098_F_83_CN',
    '033_S_1016_F_89_CN', '032_S_4429_M_83_CN', '035_S_6156_M_76_CN', '032_S_1169_F_83_CN',
    '035_S_6160_M_61_CN', '033_S_4176_M_90_CN', '033_S_4177_M_91_CN', '020_S_6185_M_83_CN',
    '024_S_6184_F_71_CN', '035_S_4464_M_76_CN', '035_S_0555_M_88_CN', '020_S_6227_F_62_CN',
    '032_S_6211_M_81_CN', '032_S_6279_M_89_CN', '020_S_6282_M_76_CN', '032_S_6294_M_82_CN',
    '032_S_6293_F_86_CN', '016_S_6381_M_73_CN', '020_S_6449_F_66_CN', '020_S_6470_M_69_CN',
    '020_S_6504_M_69_CN', '020_S_6513_F_66_CN', '020_S_6566_M_73_CN', '032_S_6699_M_67_CN',
    '032_S_6709_F_69_CN', '032_S_6701_F_71_CN', '032_S_6717_M_75_CN', '016_S_6790_M_78_CN',
    '016_S_6834_F_82_CN', '016_S_6802_F_63_CN', '033_S_4179_M_91_CN', '016_S_6853_F_67_CN',
    '033_S_6298_F_72_CN', '016_S_6892_F_66_CN', '016_S_6931_M_73_CN', '016_S_6943_M_75_CN',
    '016_S_6941_M_62_CN', '033_S_6969_M_69_CN', '016_S_6971_M_73_CN', '016_S_6934_M_67_CN',
    '033_S_5198_F_78_CN', '033_S_6266_F_70_CN', '033_S_7100_M_73_CN', '033_S_6352_M_76_CN',
    '033_S_7114_F_66_CN', '033_S_6572_F_72_CN', '033_S_10215_F_56_CN', '033_S_10092_F_56_CN',
    '033_S_10175_M_70_CN','033_S_10099_M_66_CN','016_S_6773_F_55_CN', '037_S_4410_F_74_CN',
    '037_S_4071_M_90_CN', '037_S_6032_F_66_CN', '037_S_6031_F_67_CN', '041_S_4037_M_82_CN',
    '037_S_6046_M_76_CN', '068_S_4424_F_72_CN', '037_S_4308_M_80_CN', '041_S_4427_M_77_CN',
    '068_S_0473_M_84_CN', '068_S_0210_F_84_CN', '037_S_6115_F_71_CN', '037_S_6144_F_65_CN',
    '094_S_4649_M_71_CN', '094_S_6250_F_72_CN', '094_S_6269_F_70_CN', '041_S_6226_F_68_CN',
    '094_S_6275_F_58_CN', '041_S_6292_M_77_CN', '041_S_6314_M_76_CN', '094_S_6278_F_81_CN',
    '041_S_6401_M_77_CN', '094_S_6417_M_78_CN', '094_S_6419_M_76_CN', '094_S_6440_F_68_CN',
    '041_S_5100_M_80_CN', '041_S_6447_F_71_CN', '041_S_6785_F_66_CN', '041_S_6801_F_61_CN',
    '068_S_4340_F_75_CN', '041_S_4200_F_81_CN', '041_S_6136_M_63_CN', '041_S_6159_M_78_CN',
    '068_S_0127_M_86_CN', '041_S_6786_F_90_CN', '041_S_6354_F_76_CN', '041_S_6192_F_88_CN',
    '027_S_6327_F_77_CN', '027_S_6516_M_76_CN', '027_S_6183_M_68_CN', '027_S_6577_M_69_CN',
    '021_S_6896_M_65_CN', '027_S_0074_M_93_CN', '021_S_6910_F_77_CN', '021_S_6914_M_70_CN',
    '021_S_6918_M_57_CN', '021_S_6940_M_72_CN', '021_S_0337_M_93_CN', '021_S_6987_F_66_CN',
    '021_S_6994_F_61_CN', '027_S_6001_F_77_CN', '301_S_6224_F_79_CN','007_S_4637_F_71_CN',
    '003_S_4839_M_66_CN','003_S_4840_F_62_CN', '003_S_4872_F_69_CN', '003_S_4119_M_80_CN',
    '021_S_4558_F_71_CN', '021_S_4276_F_83_CN', '016_S_4688_F_83_CN','027_S_5093_F_77_CN',
    '016_S_4121_M_91_CN', '016_S_4951_F_75_CN', '021_S_4421_F_77_CN', '027_S_5083_M_74_CN', '027_S_5169_F_66_CN',
    '027_S_0120_M_83_CN', '021_S_4335_F_77_CN', '021_S_6312_M_80_CN', '027_S_6317_F_81_CN'
])


# ----------------------------------
# Extract RD features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        rd_file = os.path.join(subj_dir, f"tensor_rd_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(rd_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (RD or atlas not found)")
        continue

    # Load RD and atlas
    rd_data = nib.load(rd_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = rd_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# Save results
np.save(os.path.join(output_dir, "Histogram_CN_RD_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_CN_RD_subjects.npy"), np.array(subj_included))

print(f"RD: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (CN, RD only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_MCI_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_46_diff_MCI_updated"),
    "54": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_54_diff_MCI_updated"),
    "55": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_55_diff_MCI_updated"),
}


atlas_dirs = {
    "46": os.path.join(base_dir, "step5_MCI_registered_data/46_diff_MCI_registered"),
    "54": os.path.join(base_dir, "step5_MCI_registered_data/54_diff_MCI_registered"),
    "55": os.path.join(base_dir, "step5_MCI_registered_data/55_diff_MCI_registered"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_MCI_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (MCI case)
# ----------------------------------
subject_ids = sorted([
    '098_S_2047_M_81_MCI',
 '109_S_2110_F_68_MCI',
 '109_S_2278_M_56_MCI',
 '021_S_2150_M_73_MCI',
 '021_S_4245_M_78_MCI',
 '021_S_2125_F_79_MCI',
 '127_S_2234_F_69_MCI',
 '127_S_4210_M_65_MCI',
 '021_S_4633_F_73_MCI',
 '127_S_4624_F_78_MCI',
 '016_S_4584_F_79_MCI',
 '027_S_4757_F_64_MCI',
 '094_S_2238_M_73_MCI',
 '007_S_4467_F_62_MCI',
 '052_S_4626_M_70_MCI',
 '057_S_4897_F_77_MCI',
 '126_S_2405_F_76_MCI',
 '007_S_2106_M_81_MCI',
 '127_S_4928_M_79_MCI',
 '094_S_2201_F_67_MCI',
 '129_S_2347_M_74_MCI',
 '007_S_4611_M_71_MCI',
 '021_S_4857_M_70_MCI',
 '057_S_4888_M_77_MCI',
 '027_S_4936_M_80_MCI',
 '027_S_2245_F_66_MCI',
 '021_S_5099_F_64_MCI',
 '094_S_2367_M_79_MCI',
 '052_S_4807_F_75_MCI',
 '052_S_4944_M_71_MCI',
 '109_S_4531_M_78_MCI',
 '135_S_4356_M_73_MCI',
 '021_S_2124_F_83_MCI',
 '016_S_2007_F_85_MCI',
 '016_S_2284_M_77_MCI',
 '094_S_4295_F_70_MCI',
 '027_S_2219_M_83_MCI',
 '109_S_4471_M_73_MCI',
 '005_S_2390_F_89_MCI',
 '027_S_4729_F_78_MCI',
 '027_S_4869_M_78_MCI',
 '027_S_2183_M_88_MCI',
 '021_S_4402_F_74_MCI',
 '094_S_2216_M_70_MCI',
 '027_S_4955_M_73_MCI',
 '003_S_4354_M_80_MCI',
 '016_S_2031_M_76_MCI',
 '127_S_4844_M_87_MCI',
 '016_S_4902_F_76_MCI',
 '098_S_2071_M_85_MCI',
 '005_S_4185_M_88_MCI',
 '027_S_4966_M_63_MCI',
 '098_S_2079_M_66_MCI',
 '007_S_4272_M_73_MCI',
 '098_S_2052_M_74_MCI',
 '003_S_0908_F_70_MCI',
 '094_S_4434_M_71_MCI',
 '029_S_2376_M_83_MCI',
 '126_S_4675_M_82_MCI',
 '127_S_2213_F_89_MCI',
 '016_S_4646_F_63_MCI',
 '109_S_4380_M_72_MCI',
 '094_S_4486_F_69_MCI',
 '126_S_4896_M_76_MCI',
 '016_S_4575_F_62_MCI',
 '021_S_2100_F_92_MCI',
 '098_S_4059_M_73_MCI',
 '126_S_4743_M_70_MCI',
 '021_S_2142_F_85_MCI',
 '027_S_4943_M_76_MCI',
 '109_S_2200_F_78_MCI',
 '052_S_4885_M_76_MCI',
 '126_S_4712_M_77_MCI',
 '057_S_2398_M_74_MCI',
 '127_S_4197_M_85_MCI',
 '129_S_4220_F_73_MCI',
 '099_S_4157_F_83_MCI',
 '129_S_4287_F_73_MCI',
 '099_S_4205_F_84_MCI',
 '109_S_4455_M_66_MCI',
 '109_S_2111_M_72_MCI',
 '021_S_2296_M_55_MCI',
 '109_S_2237_M_65_MCI',
 '109_S_4260_F_78_MCI',
 '127_S_4240_M_73_MCI',
 '003_S_4524_M_72_MCI',
 '016_S_4601_M_73_MCI',
 '057_S_4909_F_79_MCI',
 '029_S_4327_M_84_MCI',
 '016_S_5031_F_81_MCI',
 '027_S_4919_F_84_MCI',
 '052_S_4945_M_59_MCI',
 '029_S_5135_M_77_MCI',
 '126_S_4891_M_71_MCI',
 '005_S_4168_M_86_MCI',
 '099_S_2063_M_72_MCI',
 '126_S_4458_F_80_MCI',
 '099_S_4480_F_66_MCI',
 '099_S_4463_M_69_MCI',
 '021_S_2077_M_85_MCI',
 '052_S_2249_M_80_MCI',
 '016_S_5007_M_74_MCI',
 '052_S_1352_M_94_MCI',
 '126_S_2360_M_67_MCI',
 '003_S_2374_F_84_MCI',
 '094_S_4162_F_76_MCI',
 '126_S_2407_F_72_MCI',
 '099_S_4498_F_82_MCI',
 '027_S_2336_F_78_MCI',
 '135_S_4309_M_73_MCI',
 '099_S_4565_M_85_MCI',
 '052_S_1346_M_81_MCI',
 '052_S_0671_F_70_MCI',
 '109_S_4594_M_66_MCI',
 '094_S_4630_F_70_MCI',
 '135_S_4281_F_83_MCI',
 '094_S_4858_M_59_MCI',
 '027_S_4873_M_85_MCI',
 '003_S_1074_F_94_MCI',
 '007_S_2394_M_72_MCI',
  '126_S_7083_M_76_MCI',
 '126_S_4514_F_79_MCI',
 '127_S_4765_M_81_MCI',
 '021_S_4659_M_90_MCI',
 '021_S_6890_M_66_MCI',
 '129_S_2332_F_81_MCI',
 '027_S_6961_F_62_MCI',
 '021_S_0626_M_94_MCI',
 '127_S_6241_F_72_MCI',
 '098_S_6534_M_61_MCI',
 '098_S_6747_F_62_MCI',
 '027_S_6793_M_79_MCI',
 '127_S_1427_F_82_MCI',
 '099_S_6379_M_66_MCI',
 '027_S_6463_M_83_MCI',
 '098_S_6593_F_84_MCI',
 '027_S_6002_M_73_MCI',
 '098_S_6707_M_74_MCI',
 '129_S_6848_M_63_MCI',
 '126_S_4507_M_87_MCI',
 '099_S_6691_F_74_MCI',
 '027_S_6788_M_70_MCI',
 '027_S_6640_M_86_MCI',
 '027_S_6370_F_73_MCI',
 '027_S_6034_F_68_MCI',
 '027_S_6643_M_59_MCI',
 '027_S_7007_F_72_MCI',
 '127_S_6512_M_79_MCI',
 '129_S_6852_M_78_MCI',
 '099_S_6632_F_78_MCI',
 '129_S_6857_M_73_MCI',
 '027_S_6842_F_74_MCI',
 '027_S_7054_F_72_MCI',
 '027_S_7071_F_71_MCI',
 '126_S_6724_M_79_MCI',
 '021_S_4744_F_74_MCI',
 '010_S_6748_F_64_MCI',
 '021_S_0178_M_80_MCI',
 '016_S_6816_F_79_MCI', '016_S_6789_F_84_MCI', '016_S_6926_F_81_MCI',
  '033_S_7079_F_89_MCI', '033_S_7088_M_72_MCI', '033_S_10008_M_74_MCI',
  '033_S_10005_F_65_MCI', '033_S_6889_M_72_MCI', '033_S_10016_F_73_MCI'


])

# ----------------------------------
# Extract features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        fa_file = os.path.join(subj_dir, f"tensor_fa_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(fa_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (FA or atlas not found)")
        continue

    # Load FA and atlas
    fa_data = nib.load(fa_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = fa_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# Save results
np.save(os.path.join(output_dir, "Histogram_MCI_FA_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_MCI_FA_subjects.npy"), np.array(subj_included))

print(f"FA: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (MCI, FA only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_MCI_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_46_diff_MCI_updated"),
    "54": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_54_diff_MCI_updated"),
    "55": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_55_diff_MCI_updated"),
}


atlas_dirs = {
    "46": os.path.join(base_dir, "step5_MCI_registered_data/46_diff_MCI_registered"),
    "54": os.path.join(base_dir, "step5_MCI_registered_data/54_diff_MCI_registered"),
    "55": os.path.join(base_dir, "step5_MCI_registered_data/55_diff_MCI_registered"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_MCI_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 10
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (MCI case)
# ----------------------------------
subject_ids = sorted([
    '098_S_2047_M_81_MCI',
 '109_S_2110_F_68_MCI',
 '109_S_2278_M_56_MCI',
 '021_S_2150_M_73_MCI',
 '021_S_4245_M_78_MCI',
 '021_S_2125_F_79_MCI',
 '127_S_2234_F_69_MCI',
 '127_S_4210_M_65_MCI',
 '021_S_4633_F_73_MCI',
 '127_S_4624_F_78_MCI',
 '016_S_4584_F_79_MCI',
 '027_S_4757_F_64_MCI',
 '094_S_2238_M_73_MCI',
 '007_S_4467_F_62_MCI',
 '052_S_4626_M_70_MCI',
 '057_S_4897_F_77_MCI',
 '126_S_2405_F_76_MCI',
 '007_S_2106_M_81_MCI',
 '127_S_4928_M_79_MCI',
 '094_S_2201_F_67_MCI',
 '129_S_2347_M_74_MCI',
 '007_S_4611_M_71_MCI',
 '021_S_4857_M_70_MCI',
 '057_S_4888_M_77_MCI',
 '027_S_4936_M_80_MCI',
 '027_S_2245_F_66_MCI',
 '021_S_5099_F_64_MCI',
 '094_S_2367_M_79_MCI',
 '052_S_4807_F_75_MCI',
 '052_S_4944_M_71_MCI',
 '109_S_4531_M_78_MCI',
 '135_S_4356_M_73_MCI',
 '021_S_2124_F_83_MCI',
 '016_S_2007_F_85_MCI',
 '016_S_2284_M_77_MCI',
 '094_S_4295_F_70_MCI',
 '027_S_2219_M_83_MCI',
 '109_S_4471_M_73_MCI',
 '005_S_2390_F_89_MCI',
 '027_S_4729_F_78_MCI',
 '027_S_4869_M_78_MCI',
 '027_S_2183_M_88_MCI',
 '021_S_4402_F_74_MCI',
 '094_S_2216_M_70_MCI',
 '027_S_4955_M_73_MCI',
 '003_S_4354_M_80_MCI',
 '016_S_2031_M_76_MCI',
 '127_S_4844_M_87_MCI',
 '016_S_4902_F_76_MCI',
 '098_S_2071_M_85_MCI',
 '005_S_4185_M_88_MCI',
 '027_S_4966_M_63_MCI',
 '098_S_2079_M_66_MCI',
 '007_S_4272_M_73_MCI',
 '098_S_2052_M_74_MCI',
 '003_S_0908_F_70_MCI',
 '094_S_4434_M_71_MCI',
 '029_S_2376_M_83_MCI',
 '126_S_4675_M_82_MCI',
 '127_S_2213_F_89_MCI',
 '016_S_4646_F_63_MCI',
 '109_S_4380_M_72_MCI',
 '094_S_4486_F_69_MCI',
 '126_S_4896_M_76_MCI',
 '016_S_4575_F_62_MCI',
 '021_S_2100_F_92_MCI',
 '098_S_4059_M_73_MCI',
 '126_S_4743_M_70_MCI',
 '021_S_2142_F_85_MCI',
 '027_S_4943_M_76_MCI',
 '109_S_2200_F_78_MCI',
 '052_S_4885_M_76_MCI',
 '126_S_4712_M_77_MCI',
 '057_S_2398_M_74_MCI',
 '127_S_4197_M_85_MCI',
 '129_S_4220_F_73_MCI',
 '099_S_4157_F_83_MCI',
 '129_S_4287_F_73_MCI',
 '099_S_4205_F_84_MCI',
 '109_S_4455_M_66_MCI',
 '109_S_2111_M_72_MCI',
 '021_S_2296_M_55_MCI',
 '109_S_2237_M_65_MCI',
 '109_S_4260_F_78_MCI',
 '127_S_4240_M_73_MCI',
 '003_S_4524_M_72_MCI',
 '016_S_4601_M_73_MCI',
 '057_S_4909_F_79_MCI',
 '029_S_4327_M_84_MCI',
 '016_S_5031_F_81_MCI',
 '027_S_4919_F_84_MCI',
 '052_S_4945_M_59_MCI',
 '029_S_5135_M_77_MCI',
 '126_S_4891_M_71_MCI',
 '005_S_4168_M_86_MCI',
 '099_S_2063_M_72_MCI',
 '126_S_4458_F_80_MCI',
 '099_S_4480_F_66_MCI',
 '099_S_4463_M_69_MCI',
 '021_S_2077_M_85_MCI',
 '052_S_2249_M_80_MCI',
 '016_S_5007_M_74_MCI',
 '052_S_1352_M_94_MCI',
 '126_S_2360_M_67_MCI',
 '003_S_2374_F_84_MCI',
 '094_S_4162_F_76_MCI',
 '126_S_2407_F_72_MCI',
 '099_S_4498_F_82_MCI',
 '027_S_2336_F_78_MCI',
 '135_S_4309_M_73_MCI',
 '099_S_4565_M_85_MCI',
 '052_S_1346_M_81_MCI',
 '052_S_0671_F_70_MCI',
 '109_S_4594_M_66_MCI',
 '094_S_4630_F_70_MCI',
 '135_S_4281_F_83_MCI',
 '094_S_4858_M_59_MCI',
 '027_S_4873_M_85_MCI',
 '003_S_1074_F_94_MCI',
 '007_S_2394_M_72_MCI',
  '126_S_7083_M_76_MCI',
 '126_S_4514_F_79_MCI',
 '127_S_4765_M_81_MCI',
 '021_S_4659_M_90_MCI',
 '021_S_6890_M_66_MCI',
 '129_S_2332_F_81_MCI',
 '027_S_6961_F_62_MCI',
 '021_S_0626_M_94_MCI',
 '127_S_6241_F_72_MCI',
 '098_S_6534_M_61_MCI',
 '098_S_6747_F_62_MCI',
 '027_S_6793_M_79_MCI',
 '127_S_1427_F_82_MCI',
 '099_S_6379_M_66_MCI',
 '027_S_6463_M_83_MCI',
 '098_S_6593_F_84_MCI',
 '027_S_6002_M_73_MCI',
 '098_S_6707_M_74_MCI',
 '129_S_6848_M_63_MCI',
 '126_S_4507_M_87_MCI',
 '099_S_6691_F_74_MCI',
 '027_S_6788_M_70_MCI',
 '027_S_6640_M_86_MCI',
 '027_S_6370_F_73_MCI',
 '027_S_6034_F_68_MCI',
 '027_S_6643_M_59_MCI',
 '027_S_7007_F_72_MCI',
 '127_S_6512_M_79_MCI',
 '129_S_6852_M_78_MCI',
 '099_S_6632_F_78_MCI',
 '129_S_6857_M_73_MCI',
 '027_S_6842_F_74_MCI',
 '027_S_7054_F_72_MCI',
 '027_S_7071_F_71_MCI',
 '126_S_6724_M_79_MCI',
 '021_S_4744_F_74_MCI',
 '010_S_6748_F_64_MCI',
 '021_S_0178_M_80_MCI',
 '016_S_6816_F_79_MCI', '016_S_6789_F_84_MCI', '016_S_6926_F_81_MCI',
  '033_S_7079_F_89_MCI', '033_S_7088_M_72_MCI', '033_S_10008_M_74_MCI',
  '033_S_10005_F_65_MCI', '033_S_6889_M_72_MCI', '033_S_10016_F_73_MCI'


])

# ----------------------------------
# Extract features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        fa_file = os.path.join(subj_dir, f"tensor_fa_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(fa_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (FA or atlas not found)")
        continue

    # Load FA and atlas
    fa_data = nib.load(fa_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = fa_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# Save results
np.save(os.path.join(output_dir, "Histogram_MCI_FA_10bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_MCI_FA_subjects.npy"), np.array(subj_included))

print(f"FA: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (MCI, FA only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_MCI_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_46_diff_MCI_updated"),
    "54": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_54_diff_MCI_updated"),
    "55": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_55_diff_MCI_updated"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "step5_MCI_registered_data/46_diff_MCI_registered"),
    "54": os.path.join(base_dir, "step5_MCI_registered_data/54_diff_MCI_registered"),
    "55": os.path.join(base_dir, "step5_MCI_registered_data/55_diff_MCI_registered"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_MCI_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (MCI case)
# ----------------------------------
subject_ids = sorted([
    '098_S_2047_M_81_MCI',
 '109_S_2110_F_68_MCI',
 '109_S_2278_M_56_MCI',
 '021_S_2150_M_73_MCI',
 '021_S_4245_M_78_MCI',
 '021_S_2125_F_79_MCI',
 '127_S_2234_F_69_MCI',
 '127_S_4210_M_65_MCI',
 '021_S_4633_F_73_MCI',
 '127_S_4624_F_78_MCI',
 '016_S_4584_F_79_MCI',
 '027_S_4757_F_64_MCI',
 '094_S_2238_M_73_MCI',
 '007_S_4467_F_62_MCI',
 '052_S_4626_M_70_MCI',
 '057_S_4897_F_77_MCI',
 '126_S_2405_F_76_MCI',
 '007_S_2106_M_81_MCI',
 '127_S_4928_M_79_MCI',
 '094_S_2201_F_67_MCI',
 '129_S_2347_M_74_MCI',
 '007_S_4611_M_71_MCI',
 '021_S_4857_M_70_MCI',
 '057_S_4888_M_77_MCI',
 '027_S_4936_M_80_MCI',
 '027_S_2245_F_66_MCI',
 '021_S_5099_F_64_MCI',
 '094_S_2367_M_79_MCI',
 '052_S_4807_F_75_MCI',
 '052_S_4944_M_71_MCI',
 '109_S_4531_M_78_MCI',
 '135_S_4356_M_73_MCI',
 '021_S_2124_F_83_MCI',
 '016_S_2007_F_85_MCI',
 '016_S_2284_M_77_MCI',
 '094_S_4295_F_70_MCI',
 '027_S_2219_M_83_MCI',
 '109_S_4471_M_73_MCI',
 '005_S_2390_F_89_MCI',
 '027_S_4729_F_78_MCI',
 '027_S_4869_M_78_MCI',
 '027_S_2183_M_88_MCI',
 '021_S_4402_F_74_MCI',
 '094_S_2216_M_70_MCI',
 '027_S_4955_M_73_MCI',
 '003_S_4354_M_80_MCI',
 '016_S_2031_M_76_MCI',
 '127_S_4844_M_87_MCI',
 '016_S_4902_F_76_MCI',
 '098_S_2071_M_85_MCI',
 '005_S_4185_M_88_MCI',
 '027_S_4966_M_63_MCI',
 '098_S_2079_M_66_MCI',
 '007_S_4272_M_73_MCI',
 '098_S_2052_M_74_MCI',
 '003_S_0908_F_70_MCI',
 '094_S_4434_M_71_MCI',
 '029_S_2376_M_83_MCI',
 '126_S_4675_M_82_MCI',
 '127_S_2213_F_89_MCI',
 '016_S_4646_F_63_MCI',
 '109_S_4380_M_72_MCI',
 '094_S_4486_F_69_MCI',
 '126_S_4896_M_76_MCI',
 '016_S_4575_F_62_MCI',
 '021_S_2100_F_92_MCI',
 '098_S_4059_M_73_MCI',
 '126_S_4743_M_70_MCI',
 '021_S_2142_F_85_MCI',
 '027_S_4943_M_76_MCI',
 '109_S_2200_F_78_MCI',
 '052_S_4885_M_76_MCI',
 '126_S_4712_M_77_MCI',
 '057_S_2398_M_74_MCI',
 '127_S_4197_M_85_MCI',
 '129_S_4220_F_73_MCI',
 '099_S_4157_F_83_MCI',
 '129_S_4287_F_73_MCI',
 '099_S_4205_F_84_MCI',
 '109_S_4455_M_66_MCI',
 '109_S_2111_M_72_MCI',
 '021_S_2296_M_55_MCI',
 '109_S_2237_M_65_MCI',
 '109_S_4260_F_78_MCI',
 '127_S_4240_M_73_MCI',
 '003_S_4524_M_72_MCI',
 '016_S_4601_M_73_MCI',
 '057_S_4909_F_79_MCI',
 '029_S_4327_M_84_MCI',
 '016_S_5031_F_81_MCI',
 '027_S_4919_F_84_MCI',
 '052_S_4945_M_59_MCI',
 '029_S_5135_M_77_MCI',
 '126_S_4891_M_71_MCI',
 '005_S_4168_M_86_MCI',
 '099_S_2063_M_72_MCI',
 '126_S_4458_F_80_MCI',
 '099_S_4480_F_66_MCI',
 '099_S_4463_M_69_MCI',
 '021_S_2077_M_85_MCI',
 '052_S_2249_M_80_MCI',
 '016_S_5007_M_74_MCI',
 '052_S_1352_M_94_MCI',
 '126_S_2360_M_67_MCI',
 '003_S_2374_F_84_MCI',
 '094_S_4162_F_76_MCI',
 '126_S_2407_F_72_MCI',
 '099_S_4498_F_82_MCI',
 '027_S_2336_F_78_MCI',
 '135_S_4309_M_73_MCI',
 '099_S_4565_M_85_MCI',
 '052_S_1346_M_81_MCI',
 '052_S_0671_F_70_MCI',
 '109_S_4594_M_66_MCI',
 '094_S_4630_F_70_MCI',
 '135_S_4281_F_83_MCI',
 '094_S_4858_M_59_MCI',
 '027_S_4873_M_85_MCI',
 '003_S_1074_F_94_MCI',
 '007_S_2394_M_72_MCI',
  '126_S_7083_M_76_MCI',
 '126_S_4514_F_79_MCI',
 '127_S_4765_M_81_MCI',
 '021_S_4659_M_90_MCI',
 '021_S_6890_M_66_MCI',
 '129_S_2332_F_81_MCI',
 '027_S_6961_F_62_MCI',
 '021_S_0626_M_94_MCI',
 '127_S_6241_F_72_MCI',
 '098_S_6534_M_61_MCI',
 '098_S_6747_F_62_MCI',
 '027_S_6793_M_79_MCI',
 '127_S_1427_F_82_MCI',
 '099_S_6379_M_66_MCI',
 '027_S_6463_M_83_MCI',
 '098_S_6593_F_84_MCI',
 '027_S_6002_M_73_MCI',
 '098_S_6707_M_74_MCI',
 '129_S_6848_M_63_MCI',
 '126_S_4507_M_87_MCI',
 '099_S_6691_F_74_MCI',
 '027_S_6788_M_70_MCI',
 '027_S_6640_M_86_MCI',
 '027_S_6370_F_73_MCI',
 '027_S_6034_F_68_MCI',
 '027_S_6643_M_59_MCI',
 '027_S_7007_F_72_MCI',
 '127_S_6512_M_79_MCI',
 '129_S_6852_M_78_MCI',
 '099_S_6632_F_78_MCI',
 '129_S_6857_M_73_MCI',
 '027_S_6842_F_74_MCI',
 '027_S_7054_F_72_MCI',
 '027_S_7071_F_71_MCI',
 '126_S_6724_M_79_MCI',
 '021_S_4744_F_74_MCI',
 '010_S_6748_F_64_MCI',
 '021_S_0178_M_80_MCI',
 '016_S_6816_F_79_MCI', '016_S_6789_F_84_MCI', '016_S_6926_F_81_MCI',
  '033_S_7079_F_89_MCI', '033_S_7088_M_72_MCI', '033_S_10008_M_74_MCI',
  '033_S_10005_F_65_MCI', '033_S_6889_M_72_MCI', '033_S_10016_F_73_MCI'


])

# ----------------------------------
# Extract AD features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        ad_file = os.path.join(subj_dir, f"tensor_ad_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(ad_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (AD or atlas not found)")
        continue

    # Load AD and atlas
    ad_data = nib.load(ad_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = ad_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# ----------------------------------
# Save results
# ----------------------------------
np.save(os.path.join(output_dir, "Histogram_MCI_AD_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_MCI_AD_subjects.npy"), np.array(subj_included))

print(f"AD: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (MCI, AD only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_MCI_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_46_diff_MCI_updated"),
    "54": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_54_diff_MCI_updated"),
    "55": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_55_diff_MCI_updated"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "step5_MCI_registered_data/46_diff_MCI_registered"),
    "54": os.path.join(base_dir, "step5_MCI_registered_data/54_diff_MCI_registered"),
    "55": os.path.join(base_dir, "step5_MCI_registered_data/55_diff_MCI_registered"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_MCI_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (MCI case)
# ----------------------------------
subject_ids = sorted([
    '098_S_2047_M_81_MCI',
 '109_S_2110_F_68_MCI',
 '109_S_2278_M_56_MCI',
 '021_S_2150_M_73_MCI',
 '021_S_4245_M_78_MCI',
 '021_S_2125_F_79_MCI',
 '127_S_2234_F_69_MCI',
 '127_S_4210_M_65_MCI',
 '021_S_4633_F_73_MCI',
 '127_S_4624_F_78_MCI',
 '016_S_4584_F_79_MCI',
 '027_S_4757_F_64_MCI',
 '094_S_2238_M_73_MCI',
 '007_S_4467_F_62_MCI',
 '052_S_4626_M_70_MCI',
 '057_S_4897_F_77_MCI',
 '126_S_2405_F_76_MCI',
 '007_S_2106_M_81_MCI',
 '127_S_4928_M_79_MCI',
 '094_S_2201_F_67_MCI',
 '129_S_2347_M_74_MCI',
 '007_S_4611_M_71_MCI',
 '021_S_4857_M_70_MCI',
 '057_S_4888_M_77_MCI',
 '027_S_4936_M_80_MCI',
 '027_S_2245_F_66_MCI',
 '021_S_5099_F_64_MCI',
 '094_S_2367_M_79_MCI',
 '052_S_4807_F_75_MCI',
 '052_S_4944_M_71_MCI',
 '109_S_4531_M_78_MCI',
 '135_S_4356_M_73_MCI',
 '021_S_2124_F_83_MCI',
 '016_S_2007_F_85_MCI',
 '016_S_2284_M_77_MCI',
 '094_S_4295_F_70_MCI',
 '027_S_2219_M_83_MCI',
 '109_S_4471_M_73_MCI',
 '005_S_2390_F_89_MCI',
 '027_S_4729_F_78_MCI',
 '027_S_4869_M_78_MCI',
 '027_S_2183_M_88_MCI',
 '021_S_4402_F_74_MCI',
 '094_S_2216_M_70_MCI',
 '027_S_4955_M_73_MCI',
 '003_S_4354_M_80_MCI',
 '016_S_2031_M_76_MCI',
 '127_S_4844_M_87_MCI',
 '016_S_4902_F_76_MCI',
 '098_S_2071_M_85_MCI',
 '005_S_4185_M_88_MCI',
 '027_S_4966_M_63_MCI',
 '098_S_2079_M_66_MCI',
 '007_S_4272_M_73_MCI',
 '098_S_2052_M_74_MCI',
 '003_S_0908_F_70_MCI',
 '094_S_4434_M_71_MCI',
 '029_S_2376_M_83_MCI',
 '126_S_4675_M_82_MCI',
 '127_S_2213_F_89_MCI',
 '016_S_4646_F_63_MCI',
 '109_S_4380_M_72_MCI',
 '094_S_4486_F_69_MCI',
 '126_S_4896_M_76_MCI',
 '016_S_4575_F_62_MCI',
 '021_S_2100_F_92_MCI',
 '098_S_4059_M_73_MCI',
 '126_S_4743_M_70_MCI',
 '021_S_2142_F_85_MCI',
 '027_S_4943_M_76_MCI',
 '109_S_2200_F_78_MCI',
 '052_S_4885_M_76_MCI',
 '126_S_4712_M_77_MCI',
 '057_S_2398_M_74_MCI',
 '127_S_4197_M_85_MCI',
 '129_S_4220_F_73_MCI',
 '099_S_4157_F_83_MCI',
 '129_S_4287_F_73_MCI',
 '099_S_4205_F_84_MCI',
 '109_S_4455_M_66_MCI',
 '109_S_2111_M_72_MCI',
 '021_S_2296_M_55_MCI',
 '109_S_2237_M_65_MCI',
 '109_S_4260_F_78_MCI',
 '127_S_4240_M_73_MCI',
 '003_S_4524_M_72_MCI',
 '016_S_4601_M_73_MCI',
 '057_S_4909_F_79_MCI',
 '029_S_4327_M_84_MCI',
 '016_S_5031_F_81_MCI',
 '027_S_4919_F_84_MCI',
 '052_S_4945_M_59_MCI',
 '029_S_5135_M_77_MCI',
 '126_S_4891_M_71_MCI',
 '005_S_4168_M_86_MCI',
 '099_S_2063_M_72_MCI',
 '126_S_4458_F_80_MCI',
 '099_S_4480_F_66_MCI',
 '099_S_4463_M_69_MCI',
 '021_S_2077_M_85_MCI',
 '052_S_2249_M_80_MCI',
 '016_S_5007_M_74_MCI',
 '052_S_1352_M_94_MCI',
 '126_S_2360_M_67_MCI',
 '003_S_2374_F_84_MCI',
 '094_S_4162_F_76_MCI',
 '126_S_2407_F_72_MCI',
 '099_S_4498_F_82_MCI',
 '027_S_2336_F_78_MCI',
 '135_S_4309_M_73_MCI',
 '099_S_4565_M_85_MCI',
 '052_S_1346_M_81_MCI',
 '052_S_0671_F_70_MCI',
 '109_S_4594_M_66_MCI',
 '094_S_4630_F_70_MCI',
 '135_S_4281_F_83_MCI',
 '094_S_4858_M_59_MCI',
 '027_S_4873_M_85_MCI',
 '003_S_1074_F_94_MCI',
 '007_S_2394_M_72_MCI',
  '126_S_7083_M_76_MCI',
 '126_S_4514_F_79_MCI',
 '127_S_4765_M_81_MCI',
 '021_S_4659_M_90_MCI',
 '021_S_6890_M_66_MCI',
 '129_S_2332_F_81_MCI',
 '027_S_6961_F_62_MCI',
 '021_S_0626_M_94_MCI',
 '127_S_6241_F_72_MCI',
 '098_S_6534_M_61_MCI',
 '098_S_6747_F_62_MCI',
 '027_S_6793_M_79_MCI',
 '127_S_1427_F_82_MCI',
 '099_S_6379_M_66_MCI',
 '027_S_6463_M_83_MCI',
 '098_S_6593_F_84_MCI',
 '027_S_6002_M_73_MCI',
 '098_S_6707_M_74_MCI',
 '129_S_6848_M_63_MCI',
 '126_S_4507_M_87_MCI',
 '099_S_6691_F_74_MCI',
 '027_S_6788_M_70_MCI',
 '027_S_6640_M_86_MCI',
 '027_S_6370_F_73_MCI',
 '027_S_6034_F_68_MCI',
 '027_S_6643_M_59_MCI',
 '027_S_7007_F_72_MCI',
 '127_S_6512_M_79_MCI',
 '129_S_6852_M_78_MCI',
 '099_S_6632_F_78_MCI',
 '129_S_6857_M_73_MCI',
 '027_S_6842_F_74_MCI',
 '027_S_7054_F_72_MCI',
 '027_S_7071_F_71_MCI',
 '126_S_6724_M_79_MCI',
 '021_S_4744_F_74_MCI',
 '010_S_6748_F_64_MCI',
 '021_S_0178_M_80_MCI',
 '016_S_6816_F_79_MCI', '016_S_6789_F_84_MCI', '016_S_6926_F_81_MCI',
  '033_S_7079_F_89_MCI', '033_S_7088_M_72_MCI', '033_S_10008_M_74_MCI',
  '033_S_10005_F_65_MCI', '033_S_6889_M_72_MCI', '033_S_10016_F_73_MCI'


])

# ----------------------------------
# Extract MD features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        md_file = os.path.join(subj_dir, f"tensor_md_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(md_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (MD or atlas not found)")
        continue

    # Load MD and atlas
    md_data = nib.load(md_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = md_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# ----------------------------------
# Save results
# ----------------------------------
np.save(os.path.join(output_dir, "Histogram_MCI_MD_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_MCI_MD_subjects.npy"), np.array(subj_included))

print(f"MD: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (MCI, MD only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_MCI_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_46_diff_MCI_updated"),
    "54": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_54_diff_MCI_updated"),
    "55": os.path.join(base_dir, "step4_MCI_DTI_parameters/DTI_parameters_55_diff_MCI_updated"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "step5_MCI_registered_data/46_diff_MCI_registered"),
    "54": os.path.join(base_dir, "step5_MCI_registered_data/54_diff_MCI_registered"),
    "55": os.path.join(base_dir, "step5_MCI_registered_data/55_diff_MCI_registered"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_MCI_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (MCI case)
# ----------------------------------
subject_ids = sorted([
    '098_S_2047_M_81_MCI',
 '109_S_2110_F_68_MCI',
 '109_S_2278_M_56_MCI',
 '021_S_2150_M_73_MCI',
 '021_S_4245_M_78_MCI',
 '021_S_2125_F_79_MCI',
 '127_S_2234_F_69_MCI',
 '127_S_4210_M_65_MCI',
 '021_S_4633_F_73_MCI',
 '127_S_4624_F_78_MCI',
 '016_S_4584_F_79_MCI',
 '027_S_4757_F_64_MCI',
 '094_S_2238_M_73_MCI',
 '007_S_4467_F_62_MCI',
 '052_S_4626_M_70_MCI',
 '057_S_4897_F_77_MCI',
 '126_S_2405_F_76_MCI',
 '007_S_2106_M_81_MCI',
 '127_S_4928_M_79_MCI',
 '094_S_2201_F_67_MCI',
 '129_S_2347_M_74_MCI',
 '007_S_4611_M_71_MCI',
 '021_S_4857_M_70_MCI',
 '057_S_4888_M_77_MCI',
 '027_S_4936_M_80_MCI',
 '027_S_2245_F_66_MCI',
 '021_S_5099_F_64_MCI',
 '094_S_2367_M_79_MCI',
 '052_S_4807_F_75_MCI',
 '052_S_4944_M_71_MCI',
 '109_S_4531_M_78_MCI',
 '135_S_4356_M_73_MCI',
 '021_S_2124_F_83_MCI',
 '016_S_2007_F_85_MCI',
 '016_S_2284_M_77_MCI',
 '094_S_4295_F_70_MCI',
 '027_S_2219_M_83_MCI',
 '109_S_4471_M_73_MCI',
 '005_S_2390_F_89_MCI',
 '027_S_4729_F_78_MCI',
 '027_S_4869_M_78_MCI',
 '027_S_2183_M_88_MCI',
 '021_S_4402_F_74_MCI',
 '094_S_2216_M_70_MCI',
 '027_S_4955_M_73_MCI',
 '003_S_4354_M_80_MCI',
 '016_S_2031_M_76_MCI',
 '127_S_4844_M_87_MCI',
 '016_S_4902_F_76_MCI',
 '098_S_2071_M_85_MCI',
 '005_S_4185_M_88_MCI',
 '027_S_4966_M_63_MCI',
 '098_S_2079_M_66_MCI',
 '007_S_4272_M_73_MCI',
 '098_S_2052_M_74_MCI',
 '003_S_0908_F_70_MCI',
 '094_S_4434_M_71_MCI',
 '029_S_2376_M_83_MCI',
 '126_S_4675_M_82_MCI',
 '127_S_2213_F_89_MCI',
 '016_S_4646_F_63_MCI',
 '109_S_4380_M_72_MCI',
 '094_S_4486_F_69_MCI',
 '126_S_4896_M_76_MCI',
 '016_S_4575_F_62_MCI',
 '021_S_2100_F_92_MCI',
 '098_S_4059_M_73_MCI',
 '126_S_4743_M_70_MCI',
 '021_S_2142_F_85_MCI',
 '027_S_4943_M_76_MCI',
 '109_S_2200_F_78_MCI',
 '052_S_4885_M_76_MCI',
 '126_S_4712_M_77_MCI',
 '057_S_2398_M_74_MCI',
 '127_S_4197_M_85_MCI',
 '129_S_4220_F_73_MCI',
 '099_S_4157_F_83_MCI',
 '129_S_4287_F_73_MCI',
 '099_S_4205_F_84_MCI',
 '109_S_4455_M_66_MCI',
 '109_S_2111_M_72_MCI',
 '021_S_2296_M_55_MCI',
 '109_S_2237_M_65_MCI',
 '109_S_4260_F_78_MCI',
 '127_S_4240_M_73_MCI',
 '003_S_4524_M_72_MCI',
 '016_S_4601_M_73_MCI',
 '057_S_4909_F_79_MCI',
 '029_S_4327_M_84_MCI',
 '016_S_5031_F_81_MCI',
 '027_S_4919_F_84_MCI',
 '052_S_4945_M_59_MCI',
 '029_S_5135_M_77_MCI',
 '126_S_4891_M_71_MCI',
 '005_S_4168_M_86_MCI',
 '099_S_2063_M_72_MCI',
 '126_S_4458_F_80_MCI',
 '099_S_4480_F_66_MCI',
 '099_S_4463_M_69_MCI',
 '021_S_2077_M_85_MCI',
 '052_S_2249_M_80_MCI',
 '016_S_5007_M_74_MCI',
 '052_S_1352_M_94_MCI',
 '126_S_2360_M_67_MCI',
 '003_S_2374_F_84_MCI',
 '094_S_4162_F_76_MCI',
 '126_S_2407_F_72_MCI',
 '099_S_4498_F_82_MCI',
 '027_S_2336_F_78_MCI',
 '135_S_4309_M_73_MCI',
 '099_S_4565_M_85_MCI',
 '052_S_1346_M_81_MCI',
 '052_S_0671_F_70_MCI',
 '109_S_4594_M_66_MCI',
 '094_S_4630_F_70_MCI',
 '135_S_4281_F_83_MCI',
 '094_S_4858_M_59_MCI',
 '027_S_4873_M_85_MCI',
 '003_S_1074_F_94_MCI',
 '007_S_2394_M_72_MCI',
  '126_S_7083_M_76_MCI',
 '126_S_4514_F_79_MCI',
 '127_S_4765_M_81_MCI',
 '021_S_4659_M_90_MCI',
 '021_S_6890_M_66_MCI',
 '129_S_2332_F_81_MCI',
 '027_S_6961_F_62_MCI',
 '021_S_0626_M_94_MCI',
 '127_S_6241_F_72_MCI',
 '098_S_6534_M_61_MCI',
 '098_S_6747_F_62_MCI',
 '027_S_6793_M_79_MCI',
 '127_S_1427_F_82_MCI',
 '099_S_6379_M_66_MCI',
 '027_S_6463_M_83_MCI',
 '098_S_6593_F_84_MCI',
 '027_S_6002_M_73_MCI',
 '098_S_6707_M_74_MCI',
 '129_S_6848_M_63_MCI',
 '126_S_4507_M_87_MCI',
 '099_S_6691_F_74_MCI',
 '027_S_6788_M_70_MCI',
 '027_S_6640_M_86_MCI',
 '027_S_6370_F_73_MCI',
 '027_S_6034_F_68_MCI',
 '027_S_6643_M_59_MCI',
 '027_S_7007_F_72_MCI',
 '127_S_6512_M_79_MCI',
 '129_S_6852_M_78_MCI',
 '099_S_6632_F_78_MCI',
 '129_S_6857_M_73_MCI',
 '027_S_6842_F_74_MCI',
 '027_S_7054_F_72_MCI',
 '027_S_7071_F_71_MCI',
 '126_S_6724_M_79_MCI',
 '021_S_4744_F_74_MCI',
 '010_S_6748_F_64_MCI',
 '021_S_0178_M_80_MCI',
 '016_S_6816_F_79_MCI', '016_S_6789_F_84_MCI', '016_S_6926_F_81_MCI',
  '033_S_7079_F_89_MCI', '033_S_7088_M_72_MCI', '033_S_10008_M_74_MCI',
  '033_S_10005_F_65_MCI', '033_S_6889_M_72_MCI', '033_S_10016_F_73_MCI'


])

# ----------------------------------
# Extract RD features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        rd_file = os.path.join(subj_dir, f"tensor_rd_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"registered_label_image_{subject_id}.nii.gz")

        if os.path.exists(rd_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (RD or atlas not found)")
        continue

    # Load RD and atlas
    rd_data = nib.load(rd_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = rd_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# ----------------------------------
# Save results
# ----------------------------------
np.save(os.path.join(output_dir, "Histogram_MCI_RD_20bin.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_MCI_RD_subjects.npy"), np.array(subj_included))

print(f"RD: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (MCI, RD only, 9 ROIs) complete.")

import os
import numpy as np
import nibabel as nib

# ----------------------------------
# Paths
# ----------------------------------
base_dir = "/content/drive/MyDrive/TejaswiAbburi_va797/Dataset/ISBI_ADNI_AD_dataset"

subjects_dirs = {
    "46": os.path.join(base_dir, "step4_AD_DTI_parameters/DTI_parameters_46_diff_AD"),
    "54": os.path.join(base_dir, "step4_AD_DTI_parameters/DTI_parameters_54_diff_AD"),
    "55": os.path.join(base_dir, "step4_AD_DTI_parameters/DTI_parameters_55_diff_AD"),
}

atlas_dirs = {
    "46": os.path.join(base_dir, "step5_AD_registered_data/46_diff_AD_registered"),
    "54": os.path.join(base_dir, "step5_AD_registered_data/54_diff_AD_registered"),
    "55": os.path.join(base_dir, "step5_AD_registered_data/55_diff_AD_registered"),
}

output_dir = os.path.join(base_dir, "Processed_histogram_features_AD_All")
os.makedirs(output_dir, exist_ok=True)

# ----------------------------------
# ROI labels (9 regions)
# ----------------------------------
roi_labels = [5, 7, 8, 16, 18, 36, 37, 38, 39]

# ----------------------------------
# Histogram settings
# ----------------------------------
n_bins = 20
bin_edges = np.linspace(0, 1, n_bins + 1)

# ----------------------------------
# Subject list (AD case)
# ----------------------------------
subject_ids = sorted([
    '005_S_4910_F_83_AD', '007_S_4911_M_76_AD', '003_S_4892_F_76_AD',
    '005_S_4707_M_69_AD', '005_S_5038_M_83_AD', '005_S_5119_F_78_AD',
    '003_S_4136_M_68_AD', '003_S_4142_F_90_AD', '098_S_4215_M_82_AD', '098_S_4201_F_64_AD',
    '094_S_4282_M_90_AD', '029_S_4307_M_80_AD', '016_S_4353_F_56_AD', '109_S_4378_M_80_AD',
    '126_S_4494_M_73_AD', '127_S_4500_F_90_AD', '003_S_4152_M_61_AD', '016_S_4583_M_87_AD',
    '126_S_4686_M_73_AD', '021_S_4718_M_79_AD', '127_S_4749_F_78_AD', '094_S_4737_F_75_AD',
    '016_S_4591_F_66_AD', '027_S_4801_M_78_AD', '027_S_4802_M_83_AD', '016_S_4887_M_74_AD',
    '021_S_4924_M_77_AD', '016_S_4963_F_72_AD', '127_S_4992_F_65_AD', '127_S_5028_M_62_AD',
    '016_S_5032_F_78_AD', '027_S_4938_M_72_AD', '127_S_5056_M_85_AD', '027_S_4962_F_80_AD',
    '127_S_5058_M_62_AD', '027_S_4964_M_82_AD', '052_S_5062_F_71_AD', '127_S_5067_M_81_AD',
    '016_S_5057_M_77_AD', '127_S_5095_M_67_AD', '052_S_4959_M_78_AD', '016_S_4009_M_91_AD',
    '007_S_5196_F_73_AD', '127_S_4940_M_90_AD', '003_S_5165_M_79_AD', '007_S_4568_F_73_AD',
    '098_S_6601_M_73_AD', '027_S_6648_M_73_AD', '098_S_6655_M_81_AD', '098_S_6658_F_75_AD',
    '057_S_6746_M_77_AD', '027_S_6849_M_78_AD', '126_S_6683_M_68_AD', '129_S_6763_F_83_AD',
    '127_S_6433_M_79_AD', '127_S_6549_M_68_AD', '126_S_6721_M_80_AD', '027_S_6965_M_77_AD',
    '129_S_6784_M_85_AD', '057_S_6869_M_81_AD', '033_S_6976_M_58_AD', '033_S_10144_F_77_AD',
    '033_S_10147_F_65_AD', '033_S_10021_M_70_AD', '168_S_6142_F_88_AD', '168_S_6735_F_79_AD',
    '168_S_6754_M_81_AD', '168_S_6827_M_68_AD', '168_S_6828_M_84_AD', '011_S_4827_M_76_AD',
    '016_S_6708_M_56_AD', '011_S_6303_M_71_AD', '094_S_6736_M_82_AD', '033_S_6824_F_77_AD',
    '032_S_6602_M_64_AD', '032_S_6600_F_72_AD', '137_S_6812_F_73_AD', '168_S_6843_F_68_AD',
    '032_S_6855_M_75_AD', '033_S_6705_M_77_AD', '168_S_6938_M_78_AD', '016_S_7039_F_62_AD',
    '016_S_6839_F_73_AD', '168_S_6921_M_78_AD', '033_S_7066_F_82_AD', '003_S_6833_F_87_AD', '003_S_6264_M_55_AD', '011_S_6303_M_71_AD', '016_S_6708_M_56_AD', '016_S_6839_F_70_AD'
])

# ----------------------------------
# Extract features
# ----------------------------------
features_all = []
subj_included = []

for subject_id in subject_ids:
    found = False
    for diff in ["46", "54", "55"]:
        subj_dir = os.path.join(subjects_dirs[diff], subject_id)
        fa_file = os.path.join(subj_dir, f"tensor_fa_{subject_id}.nii.gz")
        atlas_file = os.path.join(atlas_dirs[diff], f"{diff}_diff_AD_registered_{subject_id}.nii.gz")


        if os.path.exists(fa_file) and os.path.exists(atlas_file):
            found = True
            break

    if not found:
        print(f"Skipping {subject_id} (FA or atlas not found)")
        continue

    # Load FA and atlas
    fa_data = nib.load(fa_file).get_fdata()
    atlas_data = nib.load(atlas_file).get_fdata().astype(int)

    subj_features = []
    for roi in roi_labels:
        roi_vals = fa_data[atlas_data == roi]
        if roi_vals.size == 0:
            hist = np.zeros(n_bins)
        else:
            hist, _ = np.histogram(roi_vals, bins=bin_edges)
            hist = hist / roi_vals.size  # normalize
        subj_features.extend(hist)

    features_all.append(subj_features)
    subj_included.append(subject_id)

features_all = np.array(features_all)

# Save results
np.save(os.path.join(output_dir, "Histogram_AD_FA_20bin_updated.npy"), features_all)
np.save(os.path.join(output_dir, "Histogram_AD_FA_subjects.npy"), np.array(subj_included))

print(f"FA: Feature matrix shape {features_all.shape}, Subjects saved {len(subj_included)}")
print("Histogram feature extraction (AD, FA only, 9 ROIs) complete.")